apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: kubekitchen
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    project: {{ .Values.global.project }}
    environment: {{ .Values.global.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
